name: DX Image Box
description: DX Image Box is a lighbox plugin for Croogo based on the Fancybox script http://fancybox.net/home

author: Mario Peshev
authorEmail: mpeshev@devrix.com
authorUrl: http://devwp.eu
